services:
  dj-ferris:
    depends_on:
      - lavalink
    restart: always
    container_name: dj-ferris
    environment:
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - APPLICATION_ID=$APPLICATION_ID
    network_mode: host
    image: dj-ferris
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4 # pin the image version to Lavalink v4
    container_name: lavalink
    restart: always
    environment:
      - _JAVA_OPTIONS=-Xmx6G # set Java options here
      - SERVER_PORT=2333 # set lavalink server port
      - LAVALINK_SERVER_PASSWORD=$LAVALINK_SERVER_PASSWORD # set password for lavalink
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
      - ./plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    network_mode: host
